/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2022-01-20 03:46:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.learncode.entities.Category;
import java.util.ArrayList;
import com.learncode.dao.PostDao;
import com.learncode.helper.DBConnection;
import com.learncode.entities.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/component/all-css.jsp", Long.valueOf(1642093074916L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.learncode.entities.User");
    _jspx_imports_classes.add("com.learncode.entities.Category");
    _jspx_imports_classes.add("com.learncode.helper.DBConnection");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.learncode.dao.PostDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("currentUser");
if (user == null) {
	response.sendRedirect("login.jsp");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Profile</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/a076d05399.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- navbar -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light sticky-top\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><span\r\n");
      out.write("			class=\"fas fa-dice-d20\"></span> ABC</a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("			data-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("				<li class=\"nav-item \"><a class=\"nav-link\" href=\"#\">Learn\r\n");
      out.write("						Code with ABC <span class=\"sr-only\">(current)</span>\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a\r\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("					aria-expanded=\"false\"> Categories </a>\r\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"#\">Programming Language</a> <a\r\n");
      out.write("							class=\"dropdown-item\" href=\"#\">Data structure</a>\r\n");
      out.write("						<div class=\"dropdown-divider\"></div>\r\n");
      out.write("						<a class=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("					</div></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Contact</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#add-post-modal\">Do Post</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"navbar-nav mr-right\">\r\n");
      out.write("				<li class=\"nav-item \"><a class=\"nav-link\" href=\"#!\"\r\n");
      out.write("					data-toggle=\"modal\" data-target=\"#profile-modal\"> <span></span>Hi,\r\n");
      out.write("						");
      out.print(user.getName());
      out.write("\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-item \"><a class=\"nav-link\" href=\"LogoutServlet\">\r\n");
      out.write("						<span></span>Logout\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- end of navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- main body -->\r\n");
      out.write("	<main>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mt-3\">\r\n");
      out.write("				<!-- first col -->\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("					<div class=\"list-group\">\r\n");
      out.write("						<a href=\"#\" onclick=\"getPosts(0, this)\" class=\"c-link list-group-item list-group-item-action active\">\r\n");
      out.write("							All post </a>\r\n");
      out.write("						");

						PostDao d = new PostDao(DBConnection.getConn());
						ArrayList<Category> listPost = d.getAllCategories();
						for (Category cc : listPost) {
						
      out.write("\r\n");
      out.write("						<a href=\"#\" onclick=\"getPosts(");
      out.print(cc.getCid() );
      out.write(",this)\" class=\"c-link list-group-item list-group-item-action\">");
      out.print(cc.getName());
      out.write("</a>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-8\" id=\"post-container\">\r\n");
      out.write("					<div class=\"container text-center\" id=\"loader\">\r\n");
      out.write("						<i class=\"fa fa-refresh fa-4x fa-spin\"></i>\r\n");
      out.write("						<h3 class=\"mt-2\">Loading...</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"container-fluid\" id=\"post-container\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- end main body -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- --profile modal--- -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"profile-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header \">\r\n");
      out.write("					<h5 class=\"modal-title \" id=\"exampleModalLabel\">ABC</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"container text-center\">\r\n");
      out.write("						<h5 class=\"modal-title mt-3\" id=\"exampleModalLabel\">");
      out.print(user.getName());
      out.write("</h5>\r\n");
      out.write("						<!-- -detail- -->\r\n");
      out.write("						<div id=\"profile-details\">\r\n");
      out.write("							<table class=\"table\">\r\n");
      out.write("								<thead class=\"thead-light\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">ID</th>\r\n");
      out.write("										<th scope=\"col\">Name</th>\r\n");
      out.write("										<th scope=\"col\">Email</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"row\">");
      out.print(user.getId());
      out.write("</th>\r\n");
      out.write("										<td>");
      out.print(user.getName());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(user.getEmail());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- -profile edit- -->\r\n");
      out.write("						<div id=\"profile-edit\" style=\"display: none;\">\r\n");
      out.write("							<h3 class=\"mt-3\">Please Edit Carefully</h3>\r\n");
      out.write("							<form action=\"EditServlet\" method=\"post\">\r\n");
      out.write("								<table class=\"table\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>ID:</td>\r\n");
      out.write("										<td>");
      out.print(user.getId());
      out.write("</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Email:</td>\r\n");
      out.write("										<td><input type=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("											value=\"");
      out.print(user.getEmail());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>Name:</td>\r\n");
      out.write("										<td><input type=\"text\" class=\"form-control\"\r\n");
      out.write("											name=\"username\" value=\"");
      out.print(user.getName());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>New Password:</td>\r\n");
      out.write("										<td><input type=\"password\" class=\"form-control\"\r\n");
      out.write("											name=\"password\" value=\"");
      out.print(user.getPassword());
      out.write("\"></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("								<div class=\"container\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\">Save</button>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Close</button>\r\n");
      out.write("					<button id=\"edit-profile-button\" type=\"button\"\r\n");
      out.write("						class=\"btn btn-primary\">Edit</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- --end of profile modal--- -->\r\n");
      out.write("\r\n");
      out.write("	<!-- -add post modal- -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"add-post-modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLongTitle\">Provide the\r\n");
      out.write("						post details...</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"add-post-form\" action=\"AddPostServlet\" method=\"post\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<select class=\"form-control\" name=\"cid\">\r\n");
      out.write("								<option selected disabled=\"disabled\">Select Category</option>\r\n");
      out.write("								");

								PostDao postd = new PostDao(DBConnection.getConn());
								ArrayList<Category> list = postd.getAllCategories();
								for (Category c : list) {
								
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(c.getCid());
      out.write('"');
      out.write('>');
      out.print(c.getName());
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<input name=\"pTitle\" type=\"text\" placeholder=\"Enter post title\"\r\n");
      out.write("								class=\"form-control\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<textarea name=\"pContent\" class=\"form-control\"\r\n");
      out.write("								style=\"height: 180px;\" placeholder=\"Enter your content\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<textarea name=\"pCode\" class=\"form-control\"\r\n");
      out.write("								style=\"height: 180px;\" placeholder=\"Enter your program (if any)\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Select your picture: </label> <br> <input name=\"pic\"\r\n");
      out.write("								type=\"file\" />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Post</button>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- -end add post modal- -->\r\n");
      out.write("	<!-- -JS- -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			let editStatus = false;\r\n");
      out.write("			$('#edit-profile-button').click(function() {\r\n");
      out.write("				if (editStatus == false) {\r\n");
      out.write("					$(\"#profile-details\").hide();\r\n");
      out.write("					$(\"#profile-edit\").show();\r\n");
      out.write("					editStatus = true;\r\n");
      out.write("					$(this).text(\"Back\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\"#profile-details\").show();\r\n");
      out.write("					$(\"#profile-edit\").hide();\r\n");
      out.write("					editStatus = false;\r\n");
      out.write("					$(this).text(\"Edit\");\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- now add post js -->\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document)\r\n");
      out.write("				.ready(\r\n");
      out.write("						function(e) {\r\n");
      out.write("							//\r\n");
      out.write("\r\n");
      out.write("							$(\"#add-post-form\")\r\n");
      out.write("									.on(\r\n");
      out.write("											\"submit\",\r\n");
      out.write("											function(event) {\r\n");
      out.write("												//this code get call when form ssubmited\r\n");
      out.write("												event.preventDefault();\r\n");
      out.write("												console.log(\"cliccked\")\r\n");
      out.write("												let form = new FormData(this);\r\n");
      out.write("\r\n");
      out.write("												$\r\n");
      out.write("														.ajax({\r\n");
      out.write("															url : \"AddPostServlet\",\r\n");
      out.write("															type : 'POST',\r\n");
      out.write("															data : form,\r\n");
      out.write("															success : function(\r\n");
      out.write("																	data,\r\n");
      out.write("																	textStatus,\r\n");
      out.write("																	jqXHR) {\r\n");
      out.write("																console\r\n");
      out.write("																		.log(data);\r\n");
      out.write("																if (data.trim() == 'error') {\r\n");
      out.write("																	swal(\r\n");
      out.write("																			\"Error!\",\r\n");
      out.write("																			\"Something wrong!\",\r\n");
      out.write("																			\"error\");\r\n");
      out.write("																} else {\r\n");
      out.write("																	swal(\r\n");
      out.write("																			\"Good job!\",\r\n");
      out.write("																			\"Saved Successfully!\",\r\n");
      out.write("																			\"success\");\r\n");
      out.write("																}\r\n");
      out.write("															},\r\n");
      out.write("															error : function(\r\n");
      out.write("																	jqXHR,\r\n");
      out.write("																	textStatus,\r\n");
      out.write("																	errorThrown) {\r\n");
      out.write("																swal(\r\n");
      out.write("																		\"Error!\",\r\n");
      out.write("																		\"Something wrong!\",\r\n");
      out.write("																		\"error\");\r\n");
      out.write("															},\r\n");
      out.write("															processData : false,\r\n");
      out.write("															contentType : false\r\n");
      out.write("														})\r\n");
      out.write("											})\r\n");
      out.write("						})\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- end add post -->\r\n");
      out.write("	<!-- Loadind post using ajax -->\r\n");
      out.write("	<script>\r\n");
      out.write("		function getPosts(catId, temp) {\r\n");
      out.write("			$(\"#loader\").show();\r\n");
      out.write("			$(\"#post-container\").hide();\r\n");
      out.write("			$(\".c-link\").removeClass('active');\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"load_posts.jsp\",\r\n");
      out.write("				data: {cid: catId},\r\n");
      out.write("				success : function(data, textStatus, jqXHR) {\r\n");
      out.write("					console.log(data);\r\n");
      out.write("					$(\"#loader\").hide();\r\n");
      out.write("					$(\"#post-container\").show();\r\n");
      out.write("					$(\"#post-container\").html(data);\r\n");
      out.write("					$(temp).addClass('active');\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		$(document).ready(function(e) {\r\n");
      out.write("			let allPostRef=$('.c-link')[0]\r\n");
      out.write("			getPosts(0, allPostRef);\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
